### PR TITLE
make versions respect #ignoredFileNames

### PR DESCRIPTION
**Pull request by pdebruic**
not sure how to do this without showing all files changed.  I used Iceberg this time.  Let me know

### CODE REVIEW

**Comment by peteruhnak** [comment]
> not sure how to do this without showing all files changed.
you can fix the line-endings afterwards in a terminal and then `git commit --amend` to fix this

**Comment by pdebruic** [comment]
OK I'll give it a shot if this is still relevant.  Let me know if its obsolete.

**Comment by pdebruic** [comment]
@peteruhnak does this repo expect LF or CRLF for line endings?

Do you want me to add a .gitattributes file that ensures they're correct?

**Comment by seandenigris** [comment]
@pdebruic The readme says: "REPO MIGRATED TO https://github.com/pharo-contributions/git-migration". Maybe the PR would be better received there?

**Comment by pdebruic** [comment]
Very likely :)  

Looks like he stopped maintenance of this a couple days after these last comments....


I'll see what I can do.

**Comment by peteruhnak** [comment]
> Looks like he stopped maintenance of this a couple days after these last comments....

I stopped at the end of 2018 or 2019 (can't remember) as I stopped working with Pharo.  (The 2020 commit is just me updating readmes for a bunch of obsolete/moved repos.)

pharo-contribs is community managed, so I guess you should just directly push your fix there (if you have rights), or ask someone (on mailing list probably) to accept the changes (as there's probably no one in a position to actually review it).

**Pull request closed without merging**
